
#include "phpglide2x_enums.h"

#define SET_CASE(c) {#c, c}

#define CREATE_CONSTANT(v) REGISTER_LONG_CONSTANT(#v, v, CONST_CS | CONST_PERSISTENT)

zend_class_entry* grAlphaBlendFnc_ce;
zend_class_entry* grAlphaSource_ce;
zend_class_entry* grAspectRatio_ce;
zend_class_entry* grBuffer_ce;
zend_class_entry* grChipID_ce;
zend_class_entry* grChromakeyMode_ce;
zend_class_entry* grCmpFnc_ce;
zend_class_entry* grColorCombineFnc_ce;
zend_class_entry* grColorFormat_ce;
zend_class_entry* grCombineFactor_ce;
zend_class_entry* grCombineFunction_ce;
zend_class_entry* grCombineLocal_ce;
zend_class_entry* grCombineOther_ce;
zend_class_entry* grCullMode_ce;
zend_class_entry* grDepth_ce;
zend_class_entry* grDepthBufferMode_ce;
zend_class_entry* grDitherMode_ce;
zend_class_entry* grEvenOdd_ce;
zend_class_entry* grFogMode_ce;
zend_class_entry* grHints_ce;
zend_class_entry* grLOD_ce;
zend_class_entry* grLfbBypassMode_ce;
zend_class_entry* grLfbSrcFmt_ce;
zend_class_entry* grLfbWriteMode_ce;
zend_class_entry* grLock_ce;
zend_class_entry* grMipMapMode_ce;
zend_class_entry* grNCCTable_ce;
zend_class_entry* grOriginLocation_ce;
zend_class_entry* grScreenRefresh_ce;
zend_class_entry* grScreenResolution_ce;
zend_class_entry* grSmoothingMode_ce;
zend_class_entry* grSstType_ce;
zend_class_entry* grTexBaseRange_ce;
zend_class_entry* grTexTable_ce;
zend_class_entry* grTextureClampMode_ce;
zend_class_entry* grTextureCombineFnc_ce;
zend_class_entry* grTextureFilterMode_ce;
zend_class_entry* grTextureFormat_ce;


typedef struct {
	const char* name;
	int value;
} EnumValue;

struct {
	zend_class_entry* enum_entry;
	EnumValue* values;  // NULL-terminated (or name==NULL) sentinel array
} grouped_enums[] = {
	{
		NULL, //grDepth_ce
		(EnumValue[]) {
			//typedef FxI32 GrChipID_ce;
			SET_CASE(GR_ZDEPTHVALUE_NEAREST),
			SET_CASE(GR_ZDEPTHVALUE_FARTHEST),
			SET_CASE(GR_WDEPTHVALUE_NEAREST),
			SET_CASE(GR_WDEPTHVALUE_FARTHEST),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grEvenOdd_ce
		(EnumValue[]) {
			SET_CASE(GR_MIPMAPLEVELMASK_EVEN),
			SET_CASE(GR_MIPMAPLEVELMASK_ODD),
			SET_CASE(GR_MIPMAPLEVELMASK_BOTH),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grChipID_ce
		(EnumValue[]) {
			SET_CASE(GR_TMU0),
			SET_CASE(GR_TMU1),
			SET_CASE(GR_TMU2),
			SET_CASE(GR_FBI),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCombineFunction_ce
		(EnumValue[]) {
			SET_CASE(GR_COMBINE_FUNCTION_ZERO),
			SET_CASE(GR_COMBINE_FUNCTION_NONE),
			SET_CASE(GR_COMBINE_FUNCTION_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER),
			SET_CASE(GR_COMBINE_FUNCTION_BLEND_OTHER),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_BLEND),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_BLEND_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL_ALPHA),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCombineFactor_ce
		(EnumValue[]) {
			SET_CASE(GR_COMBINE_FACTOR_ZERO),
			SET_CASE(GR_COMBINE_FACTOR_NONE),
			SET_CASE(GR_COMBINE_FACTOR_LOCAL),
			SET_CASE(GR_COMBINE_FACTOR_OTHER_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_TEXTURE_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_TEXTURE_RGB),
			SET_CASE(GR_COMBINE_FACTOR_DETAIL_FACTOR),
			SET_CASE(GR_COMBINE_FACTOR_LOD_FRACTION),
			SET_CASE(GR_COMBINE_FACTOR_ONE),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_OTHER_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_TEXTURE_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_DETAIL_FACTOR),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_LOD_FRACTION),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCombineLocal_ce
		(EnumValue[]) {
			SET_CASE(GR_COMBINE_LOCAL_ITERATED),
			SET_CASE(GR_COMBINE_LOCAL_CONSTANT),
			SET_CASE(GR_COMBINE_LOCAL_NONE),
			SET_CASE(GR_COMBINE_LOCAL_DEPTH),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCombineOther_ce
		(EnumValue[]) {
			SET_CASE(GR_COMBINE_OTHER_ITERATED),
			SET_CASE(GR_COMBINE_OTHER_TEXTURE),
			SET_CASE(GR_COMBINE_OTHER_CONSTANT),
			SET_CASE(GR_COMBINE_OTHER_NONE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grAlphaSource_ce
		(EnumValue[]) {
			SET_CASE(GR_ALPHASOURCE_CC_ALPHA),
			SET_CASE(GR_ALPHASOURCE_ITERATED_ALPHA),
			SET_CASE(GR_ALPHASOURCE_TEXTURE_ALPHA),
			SET_CASE(GR_ALPHASOURCE_TEXTURE_ALPHA_TIMES_ITERATED_ALPHA),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grColorCombineFnc_ce
		(EnumValue[]) {
			SET_CASE(GR_COLORCOMBINE_ZERO),
			SET_CASE(GR_COLORCOMBINE_CCRGB),
			SET_CASE(GR_COLORCOMBINE_ITRGB),
			SET_CASE(GR_COLORCOMBINE_ITRGB_DELTA0),
			SET_CASE(GR_COLORCOMBINE_DECAL_TEXTURE),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_CCRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_DELTA0),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_ADD_ALPHA),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA_ADD_ITRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_ADD_ITRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_SUB_ITRGB),
			SET_CASE(GR_COLORCOMBINE_CCRGB_BLEND_ITRGB_ON_TEXALPHA),
			SET_CASE(GR_COLORCOMBINE_DIFF_SPEC_A),
			SET_CASE(GR_COLORCOMBINE_DIFF_SPEC_B),
			SET_CASE(GR_COLORCOMBINE_ONE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grAlphaBlendFnc_ce
		(EnumValue[]) {
			SET_CASE(GR_BLEND_ZERO),
			SET_CASE(GR_BLEND_SRC_ALPHA),
			SET_CASE(GR_BLEND_SRC_COLOR),
			SET_CASE(GR_BLEND_DST_COLOR),
			SET_CASE(GR_BLEND_DST_ALPHA),
			SET_CASE(GR_BLEND_ONE),
			SET_CASE(GR_BLEND_ONE_MINUS_SRC_ALPHA),
			SET_CASE(GR_BLEND_ONE_MINUS_SRC_COLOR),
			SET_CASE(GR_BLEND_ONE_MINUS_DST_COLOR),
			SET_CASE(GR_BLEND_ONE_MINUS_DST_ALPHA),
			SET_CASE(GR_BLEND_RESERVED_8),
			SET_CASE(GR_BLEND_RESERVED_9),
			SET_CASE(GR_BLEND_RESERVED_A),
			SET_CASE(GR_BLEND_RESERVED_B),
			SET_CASE(GR_BLEND_RESERVED_C),
			SET_CASE(GR_BLEND_RESERVED_D),
			SET_CASE(GR_BLEND_RESERVED_E),
			SET_CASE(GR_BLEND_ALPHA_SATURATE),
			SET_CASE(GR_BLEND_PREFOG_COLOR),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grAspectRatio_ce
		(EnumValue[]) {
			SET_CASE(GR_ASPECT_8x1),
			SET_CASE(GR_ASPECT_4x1),
			SET_CASE(GR_ASPECT_2x1),
			SET_CASE(GR_ASPECT_1x1),
			SET_CASE(GR_ASPECT_1x2),
			SET_CASE(GR_ASPECT_1x4),
			SET_CASE(GR_ASPECT_1x8),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grBuffer_ce
		(EnumValue[]) {
			SET_CASE(GR_BUFFER_FRONTBUFFER),
			SET_CASE(GR_BUFFER_BACKBUFFER),
			SET_CASE(GR_BUFFER_AUXBUFFER),
			SET_CASE(GR_BUFFER_DEPTHBUFFER),
			SET_CASE(GR_BUFFER_ALPHABUFFER),
			SET_CASE(GR_BUFFER_TRIPLEBUFFER),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grChromakeyMode_ce
		(EnumValue[]) {
			SET_CASE(GR_CHROMAKEY_DISABLE),
			SET_CASE(GR_CHROMAKEY_ENABLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCmpFnc_ce
		(EnumValue[]) {
			SET_CASE(GR_CMP_NEVER),
			SET_CASE(GR_CMP_LESS),
			SET_CASE(GR_CMP_EQUAL),
			SET_CASE(GR_CMP_LEQUAL),
			SET_CASE(GR_CMP_GREATER),
			SET_CASE(GR_CMP_NOTEQUAL),
			SET_CASE(GR_CMP_GEQUAL),
			SET_CASE(GR_CMP_ALWAYS),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grColorFormat_ce
		(EnumValue[]) {
			SET_CASE(GR_COLORFORMAT_ARGB),
			SET_CASE(GR_COLORFORMAT_ABGR),
			SET_CASE(GR_COLORFORMAT_RGBA),
			SET_CASE(GR_COLORFORMAT_BGRA),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCullMode_ce
		(EnumValue[]) {
			SET_CASE(GR_CULL_DISABLE),
			SET_CASE(GR_CULL_NEGATIVE),
			SET_CASE(GR_CULL_POSITIVE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grDepthBufferMode_ce
		(EnumValue[]) {
			SET_CASE(GR_DEPTHBUFFER_DISABLE),
			SET_CASE(GR_DEPTHBUFFER_ZBUFFER),
			SET_CASE(GR_DEPTHBUFFER_WBUFFER),
			SET_CASE(GR_DEPTHBUFFER_ZBUFFER_COMPARE_TO_BIAS),
			SET_CASE(GR_DEPTHBUFFER_WBUFFER_COMPARE_TO_BIAS),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grDitherMode_ce
		(EnumValue[]) {
			SET_CASE(GR_DITHER_DISABLE),
			SET_CASE(GR_DITHER_2x2),
			SET_CASE(GR_DITHER_4x4),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grFogMode_ce
		(EnumValue[]) {
			SET_CASE(GR_FOG_DISABLE),
			SET_CASE(GR_FOG_WITH_ITERATED_ALPHA),
			SET_CASE(GR_FOG_WITH_TABLE),
			SET_CASE(GR_FOG_WITH_ITERATED_Z),
			SET_CASE(GR_FOG_MULT2),
			SET_CASE(GR_FOG_ADD2),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLock_ce
		(EnumValue[]) {
			SET_CASE(GR_LFB_READ_ONLY),
			SET_CASE(GR_LFB_WRITE_ONLY),
			SET_CASE(GR_LFB_IDLE),
			SET_CASE(GR_LFB_NOIDLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLfbBypassMode_ce
		(EnumValue[]) {
			SET_CASE(GR_LFBBYPASS_DISABLE),
			SET_CASE(GR_LFBBYPASS_ENABLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLfbWriteMode_ce
		(EnumValue[]) {
			SET_CASE(GR_LFBWRITEMODE_565),
			SET_CASE(GR_LFBWRITEMODE_555),
			SET_CASE(GR_LFBWRITEMODE_1555),
			SET_CASE(GR_LFBWRITEMODE_RESERVED1),
			SET_CASE(GR_LFBWRITEMODE_888),
			SET_CASE(GR_LFBWRITEMODE_8888),
			SET_CASE(GR_LFBWRITEMODE_RESERVED2),
			SET_CASE(GR_LFBWRITEMODE_RESERVED3),
			SET_CASE(GR_LFBWRITEMODE_RESERVED4),
			SET_CASE(GR_LFBWRITEMODE_RESERVED5),
			SET_CASE(GR_LFBWRITEMODE_RESERVED6),
			SET_CASE(GR_LFBWRITEMODE_RESERVED7),
			SET_CASE(GR_LFBWRITEMODE_565_DEPTH),
			SET_CASE(GR_LFBWRITEMODE_555_DEPTH),
			SET_CASE(GR_LFBWRITEMODE_1555_DEPTH),
			SET_CASE(GR_LFBWRITEMODE_ZA16),
			SET_CASE(GR_LFBWRITEMODE_ANY),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grOriginLocation_ce
		(EnumValue[]) {
			SET_CASE(GR_ORIGIN_UPPER_LEFT),
			SET_CASE(GR_ORIGIN_LOWER_LEFT),
			SET_CASE(GR_ORIGIN_ANY),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLOD_ce
		(EnumValue[]) {
			SET_CASE(GR_LOD_256),
			SET_CASE(GR_LOD_128),
			SET_CASE(GR_LOD_64),
			SET_CASE(GR_LOD_32),
			SET_CASE(GR_LOD_16),
			SET_CASE(GR_LOD_8),
			SET_CASE(GR_LOD_4),
			SET_CASE(GR_LOD_2),
			SET_CASE(GR_LOD_1),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grMipMapMode_ce
		(EnumValue[]) {
			SET_CASE(GR_MIPMAP_DISABLE),
			SET_CASE(GR_MIPMAP_NEAREST),
			SET_CASE(GR_MIPMAP_NEAREST_DITHER),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grSmoothingMode_ce
		(EnumValue[]) {
			SET_CASE(GR_SMOOTHING_DISABLE),
			SET_CASE(GR_SMOOTHING_ENABLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTextureClampMode_ce
		(EnumValue[]) {
			SET_CASE(GR_TEXTURECLAMP_WRAP),
			SET_CASE(GR_TEXTURECLAMP_CLAMP),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTextureCombineFnc_ce
		(EnumValue[]) {
			SET_CASE(GR_TEXTURECOMBINE_ZERO),
			SET_CASE(GR_TEXTURECOMBINE_DECAL),
			SET_CASE(GR_TEXTURECOMBINE_OTHER),
			SET_CASE(GR_TEXTURECOMBINE_ADD),
			SET_CASE(GR_TEXTURECOMBINE_MULTIPLY),
			SET_CASE(GR_TEXTURECOMBINE_SUBTRACT),
			SET_CASE(GR_TEXTURECOMBINE_DETAIL),
			SET_CASE(GR_TEXTURECOMBINE_DETAIL_OTHER),
			SET_CASE(GR_TEXTURECOMBINE_TRILINEAR_ODD),
			SET_CASE(GR_TEXTURECOMBINE_TRILINEAR_EVEN),
			SET_CASE(GR_TEXTURECOMBINE_ONE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTextureFilterMode_ce
		(EnumValue[]) {
			SET_CASE(GR_TEXTUREFILTER_POINT_SAMPLED),
			SET_CASE(GR_TEXTUREFILTER_BILINEAR),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTextureFormat_ce
		(EnumValue[]) {
			SET_CASE(GR_TEXFMT_8BIT),
			SET_CASE(GR_TEXFMT_RGB_332),
			SET_CASE(GR_TEXFMT_YIQ_422),
			SET_CASE(GR_TEXFMT_ALPHA_8),
			SET_CASE(GR_TEXFMT_INTENSITY_8),
			SET_CASE(GR_TEXFMT_ALPHA_INTENSITY_44),
			SET_CASE(GR_TEXFMT_P_8),
			SET_CASE(GR_TEXFMT_RSVD0),
			SET_CASE(GR_TEXFMT_RSVD1),
			SET_CASE(GR_TEXFMT_16BIT),
			SET_CASE(GR_TEXFMT_ARGB_8332),
			SET_CASE(GR_TEXFMT_AYIQ_8422),
			SET_CASE(GR_TEXFMT_RGB_565),
			SET_CASE(GR_TEXFMT_ARGB_1555),
			SET_CASE(GR_TEXFMT_ARGB_4444),
			SET_CASE(GR_TEXFMT_ALPHA_INTENSITY_88),
			SET_CASE(GR_TEXFMT_AP_88),
			SET_CASE(GR_TEXFMT_RSVD2),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTexTable_ce
		(EnumValue[]) {
			SET_CASE(GR_TEXTABLE_NCC0),
			SET_CASE(GR_TEXTABLE_NCC1),
			SET_CASE(GR_TEXTABLE_PALETTE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grNCCTable_ce
		(EnumValue[]) {
			SET_CASE(GR_NCCTABLE_NCC0),
			SET_CASE(GR_NCCTABLE_NCC1),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTexBaseRange_ce
		(EnumValue[]) {
			SET_CASE(GR_TEXBASE_256),
			SET_CASE(GR_TEXBASE_128),
			SET_CASE(GR_TEXBASE_64),
			SET_CASE(GR_TEXBASE_32_TO_1),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grSstType_ce
		(EnumValue[]) {
			SET_CASE(GR_SSTTYPE_VOODOO),
			SET_CASE(GR_SSTTYPE_SST96),
			SET_CASE(GR_SSTTYPE_AT3D),
			SET_CASE(GR_SSTTYPE_Voodoo2),
			{"GR_SSTTYPE_Banshee", 4},
			{"GR_SSTTYPE_Unknown", 5},
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grScreenRefresh_ce
		(EnumValue[]) {
			SET_CASE(GR_REFRESH_60Hz),
			SET_CASE(GR_REFRESH_70Hz),
			SET_CASE(GR_REFRESH_72Hz),
			SET_CASE(GR_REFRESH_75Hz),
			SET_CASE(GR_REFRESH_80Hz),
			SET_CASE(GR_REFRESH_90Hz),
			SET_CASE(GR_REFRESH_100Hz),
			SET_CASE(GR_REFRESH_85Hz),
			SET_CASE(GR_REFRESH_120Hz),
			SET_CASE(GR_REFRESH_NONE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grScreenResolution_ce
		(EnumValue[]) {
			SET_CASE(GR_RESOLUTION_320x200),
			SET_CASE(GR_RESOLUTION_320x240),
			SET_CASE(GR_RESOLUTION_400x256),
			SET_CASE(GR_RESOLUTION_512x384),
			SET_CASE(GR_RESOLUTION_640x200),
			SET_CASE(GR_RESOLUTION_640x350),
			SET_CASE(GR_RESOLUTION_640x400),
			SET_CASE(GR_RESOLUTION_640x480),
			SET_CASE(GR_RESOLUTION_800x600),
			SET_CASE(GR_RESOLUTION_960x720),
			SET_CASE(GR_RESOLUTION_856x480),
			SET_CASE(GR_RESOLUTION_512x256),
			SET_CASE(GR_RESOLUTION_1024x768),
			SET_CASE(GR_RESOLUTION_1280x1024),
			SET_CASE(GR_RESOLUTION_1600x1200),
			SET_CASE(GR_RESOLUTION_400x300),
			SET_CASE(GR_RESOLUTION_NONE),
			SET_CASE(GR_RESOLUTION_MIN),
			SET_CASE(GR_RESOLUTION_MAX),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grHints_ce
		(EnumValue[]) {
			SET_CASE(GR_HINTTYPE_MIN),
			SET_CASE(GR_HINT_STWHINT),
			SET_CASE(GR_HINT_FIFOCHECKHINT),
			SET_CASE(GR_HINT_FPUPRECISION),
			SET_CASE(GR_HINT_ALLOW_MIPMAP_DITHER),
			SET_CASE(GR_HINT_LFB_WRITE),
			SET_CASE(GR_HINT_LFB_PROTECT),
			SET_CASE(GR_HINT_LFB_RESET),
			SET_CASE(GR_HINTTYPE_MAX),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLfbSrcFmt_ce
		(EnumValue[]) {
			SET_CASE(GR_LFB_SRC_FMT_565),
			SET_CASE(GR_LFB_SRC_FMT_555),
			SET_CASE(GR_LFB_SRC_FMT_1555),
			SET_CASE(GR_LFB_SRC_FMT_888),
			SET_CASE(GR_LFB_SRC_FMT_8888),
			SET_CASE(GR_LFB_SRC_FMT_565_DEPTH),
			SET_CASE(GR_LFB_SRC_FMT_555_DEPTH),
			SET_CASE(GR_LFB_SRC_FMT_1555_DEPTH),
			SET_CASE(GR_LFB_SRC_FMT_ZA16),
			SET_CASE(GR_LFB_SRC_FMT_RLE16),
			{ NULL, 0 } // sentinel
		}
	},
	{ NULL, NULL }
};

int enum_to_int(zend_object* enum_obj)
{
	//we go through all the groups till we find the sentinel
	for (int i = 0; grouped_enums[i].enum_entry != NULL; i++) {
		//if we find the scope...
		if (grouped_enums[i].enum_entry == enum_obj->ce) {
			
			//we get he enumeration case name
			const char* case_name = ZSTR_VAL(Z_STR_P(zend_enum_fetch_case_name(enum_obj)));
			int len = strlen(case_name);

			//we go through the case names till we find the sentinel
			for (int j = 0; grouped_enums[i].values[j].name != NULL; j++) {
				//if we find the case name
				if (len == strlen(grouped_enums[i].values[j].name)
					&& memcmp(case_name, grouped_enums[i].values[j].name, len) == 0
				) {
					//we return the int value
					return grouped_enums[i].values[j].value;
				}
			}
			//if not found we throw an error
			zend_throw_error(NULL, "Unknown enum case");
			return 0;
		}
	}
	//if not found we throw an error
	zend_throw_error(NULL, "Unknown enum case");
	return 0;
}

zend_object* int_to_enum(int index, zend_class_entry* scope_ce)
{
	//we go through all the groups till we find the sentinel
	for (int i = 0; grouped_enums[i].enum_entry != NULL; i++) {
		//if we find the entry with the scope given...
		if (grouped_enums[i].enum_entry == scope_ce) {
			//we go through its cases till we find the sentinel
			for (int j = 0; grouped_enums[i].values[j].name != NULL; j++) {
				//if we find the one with the index...
				if (grouped_enums[i].values[j].value == index) {

					//we return the enum
					return zend_enum_get_case_cstr(scope_ce, grouped_enums[i].values[j].name);
				}
			}
			//if not found we throw an error
			zend_throw_error(NULL, "Unknown enum case");
			return NULL;
		}
	}
	//if not found we throw an error
	zend_throw_error(NULL, "Unknown enum case");
	return NULL;
}

#ifdef _DEBUG
ZEND_FUNCTION(enumToIntTest)
{
	zval* enum_zv = NULL;

	ZEND_PARSE_PARAMETERS_START(1, 1)
		Z_PARAM_ZVAL(enum_zv)
		ZEND_PARSE_PARAMETERS_END();

	RETURN_LONG(enum_to_int(Z_OBJ_P(enum_zv)));

}

ZEND_FUNCTION(intToEnumTest)
{
	zend_long value;

	char* enumClass_str = NULL;
	size_t enumClass_len;
	

	ZEND_PARSE_PARAMETERS_START(2, 2)
		Z_PARAM_LONG(value)
		Z_PARAM_STRING(enumClass_str, enumClass_len)
		
		ZEND_PARSE_PARAMETERS_END();

	zend_string* class_name = zend_string_init(enumClass_str, enumClass_len, 0);
	zend_class_entry* ce = zend_lookup_class(class_name);
	zend_string_release(class_name);

	zval zval_enum;
	ZVAL_OBJ(&zval_enum, int_to_enum(value, ce));
	RETURN_ZVAL(&zval_enum, 1, 0);
}
#endif // _DEBUG


ZEND_METHOD(GrAlphaBlendFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrAlphaSource_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrAspectRatio_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrBuffer_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrChipID_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrChromakeyMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCmpFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrColorCombineFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrColorFormat_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCombineFactor_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCombineFunction_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCombineLocal_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCombineOther_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCullMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrDepthBufferMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrDepth_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrDitherMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrEvenOdd_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrFogMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrHints_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLfbBypassMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLfbSrcFmt_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLfbWriteMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLOD_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLock_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrMipMapMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrNCCTable_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrOriginLocation_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrScreenRefresh_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrScreenResolution_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrSmoothingMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrSstType, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTexBaseRange_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTexTable_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureClampMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureCombineFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureFilterMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureFormat_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };

void phpglide2x_register_enums(INIT_FUNC_ARGS)
{
	//typedef FxI32 GrChipID_ce;
	grDepth_ce = grouped_enums[0].enum_entry = register_class_GrDepth_t();
	CREATE_CONSTANT(GR_ZDEPTHVALUE_NEAREST);
	CREATE_CONSTANT(GR_ZDEPTHVALUE_FARTHEST);
	CREATE_CONSTANT(GR_WDEPTHVALUE_NEAREST);
	CREATE_CONSTANT(GR_WDEPTHVALUE_FARTHEST);

	grEvenOdd_ce = grouped_enums[1].enum_entry = register_class_GrEvenOdd_t();
	CREATE_CONSTANT(GR_MIPMAPLEVELMASK_EVEN);
	CREATE_CONSTANT(GR_MIPMAPLEVELMASK_ODD);
	CREATE_CONSTANT(GR_MIPMAPLEVELMASK_BOTH);

	//typedef FxI32 GrChipID_ce;
	grChipID_ce = grouped_enums[2].enum_entry = register_class_GrChipID_t();
	CREATE_CONSTANT(GR_TMU0);
	CREATE_CONSTANT(GR_TMU1);
	CREATE_CONSTANT(GR_TMU2);
	CREATE_CONSTANT(GR_FBI);

	//typedef FxI32 GrCombineFunction_ce;
	grCombineFunction_ce = grouped_enums[3].enum_entry = register_class_GrCombineFunction_t();
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_ZERO);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_NONE);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_BLEND_OTHER);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_BLEND);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_BLEND_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL_ALPHA);


	//typedef FxI32 GrCombineFactor_ce;
	grCombineFactor_ce = grouped_enums[4].enum_entry = register_class_GrCombineFactor_t();
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ZERO);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_NONE);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_OTHER_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_TEXTURE_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_TEXTURE_RGB);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_DETAIL_FACTOR);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_LOD_FRACTION);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_OTHER_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_TEXTURE_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_DETAIL_FACTOR);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_LOD_FRACTION);

	//typedef FxI32 GrCombineLocal_ce;
	grCombineLocal_ce = grouped_enums[5].enum_entry = register_class_GrCombineLocal_t();
	CREATE_CONSTANT(GR_COMBINE_LOCAL_ITERATED);
	CREATE_CONSTANT(GR_COMBINE_LOCAL_CONSTANT);
	CREATE_CONSTANT(GR_COMBINE_LOCAL_NONE);
	CREATE_CONSTANT(GR_COMBINE_LOCAL_DEPTH);

	//typedef FxI32 GrCombineOther_ce;
	grCombineOther_ce = grouped_enums[6].enum_entry = register_class_GrCombineOther_t();
	CREATE_CONSTANT(GR_COMBINE_OTHER_ITERATED);
	CREATE_CONSTANT(GR_COMBINE_OTHER_TEXTURE);
	CREATE_CONSTANT(GR_COMBINE_OTHER_CONSTANT);
	CREATE_CONSTANT(GR_COMBINE_OTHER_NONE);

	//typedef FxI32 GrAlphaSource_ce;
	grAlphaSource_ce = grouped_enums[7].enum_entry = register_class_GrAlphaSource_t();
	CREATE_CONSTANT(GR_ALPHASOURCE_CC_ALPHA);
	CREATE_CONSTANT(GR_ALPHASOURCE_ITERATED_ALPHA);
	CREATE_CONSTANT(GR_ALPHASOURCE_TEXTURE_ALPHA);
	CREATE_CONSTANT(GR_ALPHASOURCE_TEXTURE_ALPHA_TIMES_ITERATED_ALPHA);

	//typedef FxI32 GrColorCombineFnc_ce;
	grColorCombineFnc_ce = grouped_enums[8].enum_entry = register_class_GrColorCombineFnc_t();
	CREATE_CONSTANT(GR_COLORCOMBINE_ZERO);
	CREATE_CONSTANT(GR_COLORCOMBINE_CCRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_ITRGB_DELTA0);
	CREATE_CONSTANT(GR_COLORCOMBINE_DECAL_TEXTURE);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_CCRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_DELTA0);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_ADD_ALPHA);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA_ADD_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_ADD_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_SUB_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_CCRGB_BLEND_ITRGB_ON_TEXALPHA);
	CREATE_CONSTANT(GR_COLORCOMBINE_DIFF_SPEC_A);
	CREATE_CONSTANT(GR_COLORCOMBINE_DIFF_SPEC_B);
	CREATE_CONSTANT(GR_COLORCOMBINE_ONE);

	//typedef FxI32 GrAlphaBlendFnc_ce;
	grAlphaBlendFnc_ce = grouped_enums[9].enum_entry = register_class_GrAlphaBlendFnc_t();
	CREATE_CONSTANT(GR_BLEND_ZERO);
	CREATE_CONSTANT(GR_BLEND_SRC_ALPHA);
	CREATE_CONSTANT(GR_BLEND_SRC_COLOR);
	CREATE_CONSTANT(GR_BLEND_DST_COLOR);
	CREATE_CONSTANT(GR_BLEND_DST_ALPHA);
	CREATE_CONSTANT(GR_BLEND_ONE);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_SRC_ALPHA);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_SRC_COLOR);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_DST_COLOR);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_DST_ALPHA);
	CREATE_CONSTANT(GR_BLEND_RESERVED_8);
	CREATE_CONSTANT(GR_BLEND_RESERVED_9);
	CREATE_CONSTANT(GR_BLEND_RESERVED_A);
	CREATE_CONSTANT(GR_BLEND_RESERVED_B);
	CREATE_CONSTANT(GR_BLEND_RESERVED_C);
	CREATE_CONSTANT(GR_BLEND_RESERVED_D);
	CREATE_CONSTANT(GR_BLEND_RESERVED_E);
	CREATE_CONSTANT(GR_BLEND_ALPHA_SATURATE);
	CREATE_CONSTANT(GR_BLEND_PREFOG_COLOR);

	//typedef FxI32 GrAspectRatio_ce;
	grAspectRatio_ce = grouped_enums[10].enum_entry = register_class_GrAspectRatio_t();
	CREATE_CONSTANT(GR_ASPECT_8x1);
	CREATE_CONSTANT(GR_ASPECT_4x1);
	CREATE_CONSTANT(GR_ASPECT_2x1);
	CREATE_CONSTANT(GR_ASPECT_1x1);
	CREATE_CONSTANT(GR_ASPECT_1x2);
	CREATE_CONSTANT(GR_ASPECT_1x4);
	CREATE_CONSTANT(GR_ASPECT_1x8);

	//typedef FxI32 GrBuffer_ce;
	grBuffer_ce = grouped_enums[11].enum_entry = register_class_GrBuffer_t();
	CREATE_CONSTANT(GR_BUFFER_FRONTBUFFER);
	CREATE_CONSTANT(GR_BUFFER_BACKBUFFER);
	CREATE_CONSTANT(GR_BUFFER_AUXBUFFER);
	CREATE_CONSTANT(GR_BUFFER_DEPTHBUFFER);
	CREATE_CONSTANT(GR_BUFFER_ALPHABUFFER);
	CREATE_CONSTANT(GR_BUFFER_TRIPLEBUFFER);

	//typedef FxI32 GrChromakeyMode_ce;
	grChromakeyMode_ce = grouped_enums[12].enum_entry = register_class_GrChromakeyMode_t();
	CREATE_CONSTANT(GR_CHROMAKEY_DISABLE);
	CREATE_CONSTANT(GR_CHROMAKEY_ENABLE);

	//typedef FxI32 GrCmpFnc_ce;
	grCmpFnc_ce = grouped_enums[13].enum_entry = register_class_GrCmpFnc_t();
	CREATE_CONSTANT(GR_CMP_NEVER);
	CREATE_CONSTANT(GR_CMP_LESS);
	CREATE_CONSTANT(GR_CMP_EQUAL);
	CREATE_CONSTANT(GR_CMP_LEQUAL);
	CREATE_CONSTANT(GR_CMP_GREATER);
	CREATE_CONSTANT(GR_CMP_NOTEQUAL);
	CREATE_CONSTANT(GR_CMP_GEQUAL);
	CREATE_CONSTANT(GR_CMP_ALWAYS);

	//typedef FxI32 GrColorFormat_ce;
	grColorFormat_ce = grouped_enums[14].enum_entry = register_class_GrColorFormat_t();
	CREATE_CONSTANT(GR_COLORFORMAT_ARGB);
	CREATE_CONSTANT(GR_COLORFORMAT_ABGR);
	CREATE_CONSTANT(GR_COLORFORMAT_RGBA);
	CREATE_CONSTANT(GR_COLORFORMAT_BGRA);

	//typedef FxI32 GrCullMode_ce;
	grCullMode_ce = grouped_enums[15].enum_entry = register_class_GrCullMode_t();
	CREATE_CONSTANT(GR_CULL_DISABLE);
	CREATE_CONSTANT(GR_CULL_NEGATIVE);
	CREATE_CONSTANT(GR_CULL_POSITIVE);

	//typedef FxI32 GrDepthBufferMode_ce;
	grDepthBufferMode_ce = grouped_enums[16].enum_entry = register_class_GrDepthBufferMode_t();
	CREATE_CONSTANT(GR_DEPTHBUFFER_DISABLE);
	CREATE_CONSTANT(GR_DEPTHBUFFER_ZBUFFER);
	CREATE_CONSTANT(GR_DEPTHBUFFER_WBUFFER);
	CREATE_CONSTANT(GR_DEPTHBUFFER_ZBUFFER_COMPARE_TO_BIAS);
	CREATE_CONSTANT(GR_DEPTHBUFFER_WBUFFER_COMPARE_TO_BIAS);

	//typedef FxI32 GrDitherMode_ce;
	grDitherMode_ce = grouped_enums[17].enum_entry = register_class_GrDitherMode_t();
	CREATE_CONSTANT(GR_DITHER_DISABLE);
	CREATE_CONSTANT(GR_DITHER_2x2);
	CREATE_CONSTANT(GR_DITHER_4x4);

	//typedef FxI32 GrFogMode_ce;
	grFogMode_ce = grouped_enums[18].enum_entry = register_class_GrFogMode_t();
	CREATE_CONSTANT(GR_FOG_DISABLE);
	CREATE_CONSTANT(GR_FOG_WITH_ITERATED_ALPHA);
	CREATE_CONSTANT(GR_FOG_WITH_TABLE);
	CREATE_CONSTANT(GR_FOG_WITH_ITERATED_Z);
	CREATE_CONSTANT(GR_FOG_MULT2);
	CREATE_CONSTANT(GR_FOG_ADD2);

	//typedef FxU32 GrLock_ce;
	grLock_ce = grouped_enums[19].enum_entry = register_class_GrLock_t();
	CREATE_CONSTANT(GR_LFB_READ_ONLY);
	CREATE_CONSTANT(GR_LFB_WRITE_ONLY);
	CREATE_CONSTANT(GR_LFB_IDLE);
	CREATE_CONSTANT(GR_LFB_NOIDLE);

	//typedef FxI32 GrLfbBypassMode_ce;
	grLfbBypassMode_ce = grouped_enums[20].enum_entry = register_class_GrLfbBypassMode_t();
	CREATE_CONSTANT(GR_LFBBYPASS_DISABLE);
	CREATE_CONSTANT(GR_LFBBYPASS_ENABLE);

	//typedef FxI32 GrLfbWriteMode_ce;
	grLfbWriteMode_ce = grouped_enums[21].enum_entry = register_class_GrLfbWriteMode_t();
	CREATE_CONSTANT(GR_LFBWRITEMODE_565);
	CREATE_CONSTANT(GR_LFBWRITEMODE_555);
	CREATE_CONSTANT(GR_LFBWRITEMODE_1555);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED1);
	CREATE_CONSTANT(GR_LFBWRITEMODE_888);
	CREATE_CONSTANT(GR_LFBWRITEMODE_8888);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED2);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED3);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED4);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED5);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED6);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED7);
	CREATE_CONSTANT(GR_LFBWRITEMODE_565_DEPTH);
	CREATE_CONSTANT(GR_LFBWRITEMODE_555_DEPTH);
	CREATE_CONSTANT(GR_LFBWRITEMODE_1555_DEPTH);
	CREATE_CONSTANT(GR_LFBWRITEMODE_ZA16);
	CREATE_CONSTANT(GR_LFBWRITEMODE_ANY);

	//typedef FxI32 GrOriginLocation_ce;
	grOriginLocation_ce = grouped_enums[22].enum_entry = register_class_GrOriginLocation_t();
	CREATE_CONSTANT(GR_ORIGIN_UPPER_LEFT);
	CREATE_CONSTANT(GR_ORIGIN_LOWER_LEFT);
	CREATE_CONSTANT(GR_ORIGIN_ANY);

	/*
	typedef struct {
		int                size;
		void               *lfbPtr;
		FxU32              strideInBytes;        
		GrLfbWriteMode_t   writeMode;
		GrOriginLocation_t origin;
	} GrLfbInfo_ce;
	*/

	//typedef FxI32 GrLOD_ce;
	grLOD_ce = grouped_enums[23].enum_entry = register_class_GrLOD_t();
	CREATE_CONSTANT(GR_LOD_256);
	CREATE_CONSTANT(GR_LOD_128);
	CREATE_CONSTANT(GR_LOD_64);
	CREATE_CONSTANT(GR_LOD_32);
	CREATE_CONSTANT(GR_LOD_16);
	CREATE_CONSTANT(GR_LOD_8);
	CREATE_CONSTANT(GR_LOD_4);
	CREATE_CONSTANT(GR_LOD_2);
	CREATE_CONSTANT(GR_LOD_1);

	//typedef FxI32 GrMipMapMode_ce;
	grMipMapMode_ce = grouped_enums[24].enum_entry = register_class_GrMipMapMode_t();
	CREATE_CONSTANT(GR_MIPMAP_DISABLE);
	CREATE_CONSTANT(GR_MIPMAP_NEAREST);
	CREATE_CONSTANT(GR_MIPMAP_NEAREST_DITHER);

	//typedef FxI32 GrSmoothingMode_ce;
	grSmoothingMode_ce = grouped_enums[25].enum_entry = register_class_GrSmoothingMode_t();
	CREATE_CONSTANT(GR_SMOOTHING_DISABLE);
	CREATE_CONSTANT(GR_SMOOTHING_ENABLE);

	//typedef FxI32 GrTextureClampMode_ce;
	grTextureClampMode_ce = grouped_enums[26].enum_entry = register_class_GrTextureClampMode_t();
	CREATE_CONSTANT(GR_TEXTURECLAMP_WRAP);
	CREATE_CONSTANT(GR_TEXTURECLAMP_CLAMP);

	//typedef FxI32 GrTextureCombineFnc_ce;
	grTextureCombineFnc_ce = grouped_enums[27].enum_entry = register_class_GrTextureCombineFnc_t();
	CREATE_CONSTANT(GR_TEXTURECOMBINE_ZERO);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_DECAL);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_OTHER);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_ADD);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_MULTIPLY);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_SUBTRACT);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_DETAIL);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_DETAIL_OTHER);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_TRILINEAR_ODD);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_TRILINEAR_EVEN);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_ONE);

	//typedef FxI32 GrTextureFilterMode_ce;
	grTextureFilterMode_ce = grouped_enums[28].enum_entry = register_class_GrTextureFilterMode_t();
	CREATE_CONSTANT(GR_TEXTUREFILTER_POINT_SAMPLED);
	CREATE_CONSTANT(GR_TEXTUREFILTER_BILINEAR);
	
	//typedef FxI32 GrTextureFormat_ce;
	grTextureFormat_ce = grouped_enums[29].enum_entry = register_class_GrTextureFormat_t();
	CREATE_CONSTANT(GR_TEXFMT_8BIT);
	CREATE_CONSTANT(GR_TEXFMT_RGB_332);
	CREATE_CONSTANT(GR_TEXFMT_YIQ_422);
	CREATE_CONSTANT(GR_TEXFMT_ALPHA_8);
	CREATE_CONSTANT(GR_TEXFMT_INTENSITY_8);
	CREATE_CONSTANT(GR_TEXFMT_ALPHA_INTENSITY_44);
	CREATE_CONSTANT(GR_TEXFMT_P_8);
	CREATE_CONSTANT(GR_TEXFMT_RSVD0);
	CREATE_CONSTANT(GR_TEXFMT_RSVD1);
	CREATE_CONSTANT(GR_TEXFMT_16BIT);
	CREATE_CONSTANT(GR_TEXFMT_ARGB_8332);
	CREATE_CONSTANT(GR_TEXFMT_AYIQ_8422);
	CREATE_CONSTANT(GR_TEXFMT_RGB_565);
	CREATE_CONSTANT(GR_TEXFMT_ARGB_1555);
	CREATE_CONSTANT(GR_TEXFMT_ARGB_4444);
	CREATE_CONSTANT(GR_TEXFMT_ALPHA_INTENSITY_88);
	CREATE_CONSTANT(GR_TEXFMT_AP_88);
	CREATE_CONSTANT(GR_TEXFMT_RSVD2);

	//typedef FxU32 GrTexTable_ce;
	grTexTable_ce = grouped_enums[30].enum_entry = register_class_GrTexTable_t();
	CREATE_CONSTANT(GR_TEXTABLE_NCC0);
	CREATE_CONSTANT(GR_TEXTABLE_NCC1);
	CREATE_CONSTANT(GR_TEXTABLE_PALETTE);
	
	//typedef FxU32 GrNCCTable_ce;
	grNCCTable_ce = grouped_enums[31].enum_entry = register_class_GrNCCTable_t();
	CREATE_CONSTANT(GR_NCCTABLE_NCC0);
	CREATE_CONSTANT(GR_NCCTABLE_NCC1);

	//typedef FxU32 GrTexBaseRange_ce;
	grTexBaseRange_ce = grouped_enums[32].enum_entry = register_class_GrTexBaseRange_t();
	CREATE_CONSTANT(GR_TEXBASE_256);
	CREATE_CONSTANT(GR_TEXBASE_128);
	CREATE_CONSTANT(GR_TEXBASE_64);
	CREATE_CONSTANT(GR_TEXBASE_32_TO_1);

	/*
	typedef struct _GrState_s {
	  char pad[GLIDE_STATE_PAD_SIZE];
	} GrState;
	*/

	/*
	typedef struct {
		GrLOD_t           smallLod;
		GrLOD_t           largeLod;
		GrAspectRatio_t   aspectRatio;
		GrTextureFormat_t format;
		void              *data;
	} GrTexInfo;
	*/

	//typedef int GrSstType;
	grSstType_ce = grouped_enums[33].enum_entry = register_class_GrSstType();
	CREATE_CONSTANT(GR_SSTTYPE_VOODOO);
	CREATE_CONSTANT(GR_SSTTYPE_SST96);
	CREATE_CONSTANT(GR_SSTTYPE_AT3D);
	CREATE_CONSTANT(GR_SSTTYPE_Voodoo2);


	grScreenRefresh_ce = grouped_enums[34].enum_entry = register_class_GrScreenRefresh_t();

	CREATE_CONSTANT(GR_REFRESH_60Hz);
	CREATE_CONSTANT(GR_REFRESH_70Hz);
	CREATE_CONSTANT(GR_REFRESH_72Hz);
	CREATE_CONSTANT(GR_REFRESH_75Hz);
	CREATE_CONSTANT(GR_REFRESH_80Hz);
	CREATE_CONSTANT(GR_REFRESH_90Hz);
	CREATE_CONSTANT(GR_REFRESH_100Hz);
	CREATE_CONSTANT(GR_REFRESH_85Hz);
	CREATE_CONSTANT(GR_REFRESH_120Hz);
	CREATE_CONSTANT(GR_REFRESH_NONE);

	//typedef FxI32 GrScreenResolution_ce;
	grScreenResolution_ce = grouped_enums[35].enum_entry = register_class_GrScreenResolution_t();

	CREATE_CONSTANT(GR_RESOLUTION_320x200);
	CREATE_CONSTANT(GR_RESOLUTION_320x240);
	CREATE_CONSTANT(GR_RESOLUTION_400x256);
	CREATE_CONSTANT(GR_RESOLUTION_512x384);
	CREATE_CONSTANT(GR_RESOLUTION_640x200);
	CREATE_CONSTANT(GR_RESOLUTION_640x350);
	CREATE_CONSTANT(GR_RESOLUTION_640x400);
	CREATE_CONSTANT(GR_RESOLUTION_640x480);
	CREATE_CONSTANT(GR_RESOLUTION_800x600);
	CREATE_CONSTANT(GR_RESOLUTION_960x720);
	CREATE_CONSTANT(GR_RESOLUTION_856x480);
	CREATE_CONSTANT(GR_RESOLUTION_512x256);
	CREATE_CONSTANT(GR_RESOLUTION_1024x768);
	CREATE_CONSTANT(GR_RESOLUTION_1280x1024);
	CREATE_CONSTANT(GR_RESOLUTION_1600x1200);
	CREATE_CONSTANT(GR_RESOLUTION_400x300);
	CREATE_CONSTANT(GR_RESOLUTION_NONE);
	CREATE_CONSTANT(GR_RESOLUTION_MIN);
	CREATE_CONSTANT(GR_RESOLUTION_MAX);

	//typedef FxU32 GrHint_t;
	grHints_ce = grouped_enums[36].enum_entry = register_class_GrHints_t();
	CREATE_CONSTANT(GR_HINTTYPE_MIN);
	CREATE_CONSTANT(GR_HINT_STWHINT);
	CREATE_CONSTANT(GR_HINT_FIFOCHECKHINT);
	CREATE_CONSTANT(GR_HINT_ALLOW_MIPMAP_DITHER);
	CREATE_CONSTANT(GR_HINT_LFB_WRITE);
	CREATE_CONSTANT(GR_HINT_LFB_PROTECT);
	CREATE_CONSTANT(GR_HINT_LFB_RESET);
	CREATE_CONSTANT(GR_HINTTYPE_MAX);

	//typedef FxU32 GrLfbSrcFmt_t;
	grLfbSrcFmt_ce = grouped_enums[37].enum_entry = register_class_GrLfbSrcFmt_t();
	CREATE_CONSTANT(GR_LFB_SRC_FMT_565);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_555);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_1555);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_888);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_8888);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_565_DEPTH);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_555_DEPTH);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_1555_DEPTH);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_ZA16);
	CREATE_CONSTANT(GR_LFB_SRC_FMT_RLE16);
}