#include "phpglide3x_enums.h"

#define SET_CASE(c) {#c, c}

#define CREATE_CONSTANT(v) REGISTER_LONG_CONSTANT(#v, v, CONST_CS | CONST_PERSISTENT)

zend_class_entry* grCombineFunction_ce;
zend_class_entry* grCombineFactor_ce;
zend_class_entry* grCombineLocal_ce;
zend_class_entry* grCombineOther_ce;
zend_class_entry* grAlphaSource_ce;
zend_class_entry* grColorCombineFnc_ce;
zend_class_entry* grAlphaBlendFnc_ce;
zend_class_entry* grAspectRatio_ce;
zend_class_entry* grBuffer_ce;
zend_class_entry* grChromakeyMode_ce;
zend_class_entry* grChromaRangeMode_ce;
zend_class_entry* grTexChromakeyMode_ce;
zend_class_entry* grCmpFnc_ce;
zend_class_entry* grColorFormat_ce;
zend_class_entry* grCullMode_ce;
zend_class_entry* grDepthBufferMode_ce;
zend_class_entry* grDitherMode_ce;
zend_class_entry* grFogMode_ce;
zend_class_entry* grLock_ce;
zend_class_entry* grLfbBypassMode_ce;
zend_class_entry* grLfbWriteMode_ce;
zend_class_entry* grOriginLocation_ce;
zend_class_entry* grLOD_ce;
zend_class_entry* grMipMapMode_ce;
zend_class_entry* grSmoothingMode_ce;
zend_class_entry* grTextureClampMode_ce;
zend_class_entry* grTextureCombineFnc_ce;
zend_class_entry* grTextureFilterMode_ce;
zend_class_entry* grTextureFormat_ce;
zend_class_entry* grTexTable_ce;
zend_class_entry* grNCCTable_ce;
zend_class_entry* grTexBaseRange_ce;
zend_class_entry* grEnableMode_ce;
zend_class_entry* grCoordinateSpaceMode_ce;
zend_class_entry* grDataStrips_ce;
zend_class_entry* grParams_ce;
zend_class_entry* grMode_ce;
zend_class_entry* grVertex_ce;
zend_class_entry* grGet_ce;
zend_class_entry* grString_ce;
zend_class_entry* grScreenRefresh_ce;
zend_class_entry* grScreenResolution_ce;

typedef struct {
	const char* name;
	int value;
} EnumValue;

struct {
	zend_class_entry* enum_entry;
	EnumValue* values;  // NULL-terminated (or name==NULL) sentinel array
} grouped_enums[] = {
	{
		NULL, //grCombineFunction_ce
		(EnumValue[]) {
			//typedef FxI32 GrCombineFunction_t;
			SET_CASE(GR_COMBINE_FUNCTION_ZERO),
			SET_CASE(GR_COMBINE_FUNCTION_NONE),
			SET_CASE(GR_COMBINE_FUNCTION_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER),
			SET_CASE(GR_COMBINE_FUNCTION_BLEND_OTHER),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_BLEND),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_BLEND_LOCAL),
			SET_CASE(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL_ALPHA),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCombineFactor_ce
		(EnumValue[]) {
			//typedef FxI32 GrCombineFactor_t;
			SET_CASE(GR_COMBINE_FACTOR_ZERO),
			SET_CASE(GR_COMBINE_FACTOR_NONE),
			SET_CASE(GR_COMBINE_FACTOR_LOCAL),
			SET_CASE(GR_COMBINE_FACTOR_OTHER_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_TEXTURE_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_TEXTURE_RGB),
			SET_CASE(GR_COMBINE_FACTOR_DETAIL_FACTOR),
			SET_CASE(GR_COMBINE_FACTOR_LOD_FRACTION),
			SET_CASE(GR_COMBINE_FACTOR_ONE),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_OTHER_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_TEXTURE_ALPHA),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_DETAIL_FACTOR),
			SET_CASE(GR_COMBINE_FACTOR_ONE_MINUS_LOD_FRACTION),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCombineLocal_ce
		(EnumValue[]) {
			//typedef FxI32 GrCombineLocal_t;
			SET_CASE(GR_COMBINE_LOCAL_ITERATED),
			SET_CASE(GR_COMBINE_LOCAL_CONSTANT),
			SET_CASE(GR_COMBINE_LOCAL_NONE),
			SET_CASE(GR_COMBINE_LOCAL_DEPTH),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCombineOther_ce
		(EnumValue[]) {
			//typedef FxI32 GrCombineOther_t;
			SET_CASE(GR_COMBINE_OTHER_ITERATED),
			SET_CASE(GR_COMBINE_OTHER_TEXTURE),
			SET_CASE(GR_COMBINE_OTHER_CONSTANT),
			SET_CASE(GR_COMBINE_OTHER_NONE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grAlphaSource_ce
		(EnumValue[]) {
			//typedef FxI32 GrAlphaSource_t;
			SET_CASE(GR_ALPHASOURCE_CC_ALPHA),
			SET_CASE(GR_ALPHASOURCE_ITERATED_ALPHA),
			SET_CASE(GR_ALPHASOURCE_TEXTURE_ALPHA),
			SET_CASE(GR_ALPHASOURCE_TEXTURE_ALPHA_TIMES_ITERATED_ALPHA),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grColorCombineFnc_ce
		(EnumValue[]) {
			//typedef FxI32 GrColorCombineFnc_t;
			SET_CASE(GR_COLORCOMBINE_ZERO),
			SET_CASE(GR_COLORCOMBINE_CCRGB),
			SET_CASE(GR_COLORCOMBINE_ITRGB),
			SET_CASE(GR_COLORCOMBINE_ITRGB_DELTA0),
			SET_CASE(GR_COLORCOMBINE_DECAL_TEXTURE),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_CCRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_DELTA0),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_ADD_ALPHA),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA_ADD_ITRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_ADD_ITRGB),
			SET_CASE(GR_COLORCOMBINE_TEXTURE_SUB_ITRGB),
			SET_CASE(GR_COLORCOMBINE_CCRGB_BLEND_ITRGB_ON_TEXALPHA),
			SET_CASE(GR_COLORCOMBINE_DIFF_SPEC_A),
			SET_CASE(GR_COLORCOMBINE_DIFF_SPEC_B),
			SET_CASE(GR_COLORCOMBINE_ONE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grAlphaBlendFnc_ce
		(EnumValue[]) {
			//typedef FxI32 GrAlphaBlendFnc_t;
			SET_CASE(GR_BLEND_ZERO),
			SET_CASE(GR_BLEND_SRC_ALPHA),
			SET_CASE(GR_BLEND_SRC_COLOR),
			SET_CASE(GR_BLEND_DST_COLOR),
			SET_CASE(GR_BLEND_DST_ALPHA),
			SET_CASE(GR_BLEND_ONE),
			SET_CASE(GR_BLEND_ONE_MINUS_SRC_ALPHA),
			SET_CASE(GR_BLEND_ONE_MINUS_SRC_COLOR),
			SET_CASE(GR_BLEND_ONE_MINUS_DST_COLOR),
			SET_CASE(GR_BLEND_ONE_MINUS_DST_ALPHA),
			SET_CASE(GR_BLEND_RESERVED_8),
			SET_CASE(GR_BLEND_RESERVED_9),
			SET_CASE(GR_BLEND_RESERVED_A),
			SET_CASE(GR_BLEND_RESERVED_B),
			SET_CASE(GR_BLEND_RESERVED_C),
			SET_CASE(GR_BLEND_RESERVED_D),
			SET_CASE(GR_BLEND_RESERVED_E),
			SET_CASE(GR_BLEND_ALPHA_SATURATE),
			SET_CASE(GR_BLEND_PREFOG_COLOR),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grAspectRatio_ce
		(EnumValue[]) {
			//typedef FxI32 GrAspectRatio_t;
			SET_CASE(GR_ASPECT_LOG2_8x1),
			SET_CASE(GR_ASPECT_LOG2_4x1),
			SET_CASE(GR_ASPECT_LOG2_2x1),
			SET_CASE(GR_ASPECT_LOG2_1x1),
			SET_CASE(GR_ASPECT_LOG2_1x2),
			SET_CASE(GR_ASPECT_LOG2_1x4),
			SET_CASE(GR_ASPECT_LOG2_1x8),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grBuffer_ce
		(EnumValue[]) {
			//typedef FxI32 GrBuffer_t;
			SET_CASE(GR_BUFFER_FRONTBUFFER),
			SET_CASE(GR_BUFFER_BACKBUFFER),
			SET_CASE(GR_BUFFER_AUXBUFFER),
			SET_CASE(GR_BUFFER_DEPTHBUFFER),
			SET_CASE(GR_BUFFER_ALPHABUFFER),
			SET_CASE(GR_BUFFER_TRIPLEBUFFER),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grChromakeyMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrChromakeyMode_t;
			SET_CASE(GR_CHROMAKEY_DISABLE),
			SET_CASE(GR_CHROMAKEY_ENABLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grChromaRangeMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrChromaRangeMode_t;
			SET_CASE(GR_CHROMARANGE_RGB_ALL_EXT),
			SET_CASE(GR_CHROMARANGE_DISABLE_EXT),
			SET_CASE(GR_CHROMARANGE_ENABLE_EXT),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTexChromakeyMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrTexChromakeyMode_t;
			SET_CASE(GR_TEXCHROMA_DISABLE_EXT),
			SET_CASE(GR_TEXCHROMA_ENABLE_EXT),
			SET_CASE(GR_TEXCHROMARANGE_RGB_ALL_EXT),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCmpFnc_ce
		(EnumValue[]) {
			//typedef FxI32 GrCmpFnc_t;
			SET_CASE(GR_CMP_NEVER),
			SET_CASE(GR_CMP_LESS),
			SET_CASE(GR_CMP_EQUAL),
			SET_CASE(GR_CMP_LEQUAL),
			SET_CASE(GR_CMP_GREATER),
			SET_CASE(GR_CMP_NOTEQUAL),
			SET_CASE(GR_CMP_GEQUAL),
			SET_CASE(GR_CMP_ALWAYS),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grColorFormat_ce
		(EnumValue[]) {
			//typedef FxI32 GrColorFormat_t;
			SET_CASE(GR_COLORFORMAT_ARGB),
			SET_CASE(GR_COLORFORMAT_ABGR),
			SET_CASE(GR_COLORFORMAT_RGBA),
			SET_CASE(GR_COLORFORMAT_BGRA),
			{ NULL, 0 }
		}
	},
	{
		NULL, //grCullMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrCullMode_t;
			SET_CASE(GR_CULL_DISABLE),
			SET_CASE(GR_CULL_NEGATIVE),
			SET_CASE(GR_CULL_POSITIVE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grDepthBufferMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrDepthBufferMode_t;
			SET_CASE(GR_DEPTHBUFFER_DISABLE),
			SET_CASE(GR_DEPTHBUFFER_ZBUFFER),
			SET_CASE(GR_DEPTHBUFFER_WBUFFER),
			SET_CASE(GR_DEPTHBUFFER_ZBUFFER_COMPARE_TO_BIAS),
			SET_CASE(GR_DEPTHBUFFER_WBUFFER_COMPARE_TO_BIAS),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grDitherMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrDitherMode_t;
			SET_CASE(GR_DITHER_DISABLE),
			SET_CASE(GR_DITHER_2x2),
			SET_CASE(GR_DITHER_4x4),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grFogMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrFogMode_t;
			SET_CASE(GR_FOG_DISABLE),
			SET_CASE(GR_FOG_WITH_TABLE_ON_FOGCOORD_EXT),
			SET_CASE(GR_FOG_WITH_TABLE_ON_Q),
			SET_CASE(GR_FOG_WITH_TABLE_ON_W),
			SET_CASE(GR_FOG_WITH_ITERATED_Z),
			SET_CASE(GR_FOG_MULT2),
			SET_CASE(GR_FOG_ADD2),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLock_ce
		(EnumValue[]) {
			//typedef FxU32 GrLock_t;
			SET_CASE(GR_LFB_READ_ONLY),
			SET_CASE(GR_LFB_WRITE_ONLY),
			SET_CASE(GR_LFB_IDLE),
			SET_CASE(GR_LFB_NOIDLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLfbBypassMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrLfbBypassMode_t;
			SET_CASE(GR_LFBBYPASS_DISABLE),
			SET_CASE(GR_LFBBYPASS_ENABLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grLfbWriteMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrLfbWriteMode_t;
			SET_CASE(GR_LFBWRITEMODE_565),
			SET_CASE(GR_LFBWRITEMODE_555),
			SET_CASE(GR_LFBWRITEMODE_1555),
			SET_CASE(GR_LFBWRITEMODE_RESERVED1),
			SET_CASE(GR_LFBWRITEMODE_888),
			SET_CASE(GR_LFBWRITEMODE_8888),
			SET_CASE(GR_LFBWRITEMODE_RESERVED2),
			SET_CASE(GR_LFBWRITEMODE_RESERVED3),
			SET_CASE(GR_LFBWRITEMODE_RESERVED4),
			SET_CASE(GR_LFBWRITEMODE_RESERVED5),
			SET_CASE(GR_LFBWRITEMODE_RESERVED6),
			SET_CASE(GR_LFBWRITEMODE_RESERVED7),
			SET_CASE(GR_LFBWRITEMODE_565_DEPTH),
			SET_CASE(GR_LFBWRITEMODE_555_DEPTH),
			SET_CASE(GR_LFBWRITEMODE_1555_DEPTH),
			SET_CASE(GR_LFBWRITEMODE_ZA16),
			SET_CASE(GR_LFBWRITEMODE_ANY),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grOriginLocation_ce
		(EnumValue[]) {
			//typedef FxI32 GrOriginLocation_t;
			SET_CASE(GR_ORIGIN_UPPER_LEFT),
			SET_CASE(GR_ORIGIN_LOWER_LEFT),
			SET_CASE(GR_ORIGIN_ANY),
			{ NULL, 0 } // sentinel
		}
	},

		/*
		typedef struct {
			int                size;
			void               *lfbPtr;
			FxU32              strideInBytes;
			GrLfbWriteMode_t   writeMode;
			GrOriginLocation_t origin;
		} GrLfbInfo_t;
		*/

	{
		NULL, //grLOD_ce
		(EnumValue[]) {
			//typedef FxI32 GrLOD_t;
			SET_CASE(GR_LOD_LOG2_256),
			SET_CASE(GR_LOD_LOG2_128),
			SET_CASE(GR_LOD_LOG2_64),
			SET_CASE(GR_LOD_LOG2_32),
			SET_CASE(GR_LOD_LOG2_16),
			SET_CASE(GR_LOD_LOG2_8),
			SET_CASE(GR_LOD_LOG2_4),
			SET_CASE(GR_LOD_LOG2_2),
			SET_CASE(GR_LOD_LOG2_1),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grMipMapMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrMipMapMode_t;
			SET_CASE(GR_MIPMAP_DISABLE),
			SET_CASE(GR_MIPMAP_NEAREST),
			SET_CASE(GR_MIPMAP_NEAREST_DITHER),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grSmoothingMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrSmoothingMode_t;
			SET_CASE(GR_SMOOTHING_DISABLE),
			SET_CASE(GR_SMOOTHING_ENABLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTextureClampMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrTextureClampMode_t;
			SET_CASE(GR_TEXTURECLAMP_WRAP),
			SET_CASE(GR_TEXTURECLAMP_CLAMP),
			SET_CASE(GR_TEXTURECLAMP_MIRROR_EXT),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTextureCombineFnc_ce
		(EnumValue[]) {
			//typedef FxI32 GrTextureCombineFnc_t;
			SET_CASE(GR_TEXTURECOMBINE_ZERO),
			SET_CASE(GR_TEXTURECOMBINE_DECAL),
			SET_CASE(GR_TEXTURECOMBINE_OTHER),
			SET_CASE(GR_TEXTURECOMBINE_ADD),
			SET_CASE(GR_TEXTURECOMBINE_MULTIPLY),
			SET_CASE(GR_TEXTURECOMBINE_SUBTRACT),
			SET_CASE(GR_TEXTURECOMBINE_DETAIL),
			SET_CASE(GR_TEXTURECOMBINE_DETAIL_OTHER),
			SET_CASE(GR_TEXTURECOMBINE_TRILINEAR_ODD),
			SET_CASE(GR_TEXTURECOMBINE_TRILINEAR_EVEN),
			SET_CASE(GR_TEXTURECOMBINE_ONE),
			{ NULL, 0 }
		}
	},
	{
		NULL, //grTextureFilterMode_ce
		(EnumValue[]) {
			//typedef FxI32 GrTextureFilterMode_t;
			SET_CASE(GR_TEXTUREFILTER_POINT_SAMPLED),
			SET_CASE(GR_TEXTUREFILTER_BILINEAR),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTextureFormat_ce
		(EnumValue[]) {
			//typedef FxI32 GrTextureFormat_t;
			SET_CASE(GR_TEXFMT_8BIT),
			SET_CASE(GR_TEXFMT_RGB_332),
			SET_CASE(GR_TEXFMT_YIQ_422),
			SET_CASE(GR_TEXFMT_ALPHA_8),
			SET_CASE(GR_TEXFMT_INTENSITY_8),
			SET_CASE(GR_TEXFMT_ALPHA_INTENSITY_44),
			SET_CASE(GR_TEXFMT_P_8),
			SET_CASE(GR_TEXFMT_RSVD0),
			SET_CASE(GR_TEXFMT_RSVD1),
			SET_CASE(GR_TEXFMT_16BIT),
			SET_CASE(GR_TEXFMT_ARGB_8332),
			SET_CASE(GR_TEXFMT_AYIQ_8422),
			SET_CASE(GR_TEXFMT_RGB_565),
			SET_CASE(GR_TEXFMT_ARGB_1555),
			SET_CASE(GR_TEXFMT_ARGB_4444),
			SET_CASE(GR_TEXFMT_ALPHA_INTENSITY_88),
			SET_CASE(GR_TEXFMT_AP_88),
			SET_CASE(GR_TEXFMT_RSVD2),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTexTable_ce
		(EnumValue[]) {
			//typedef FxU32 GrTexTable_t;
			SET_CASE(GR_TEXTABLE_NCC0),
			SET_CASE(GR_TEXTABLE_NCC1),
			SET_CASE(GR_TEXTABLE_PALETTE),
			SET_CASE(GR_TEXTABLE_PALETTE_6666_EXT),
			{ NULL, 0 }
		}
	},
	{
		NULL, //grNCCTable_ce
		(EnumValue[]) {
			//typedef FxU32 GrNCCTable_t;
			SET_CASE(GR_NCCTABLE_NCC0),
			SET_CASE(GR_NCCTABLE_NCC1),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grTexBaseRange_ce
		(EnumValue[]) {
			//typedef FxU32 GrTexBaseRange_t;
			SET_CASE(GR_TEXBASE_256),
			SET_CASE(GR_TEXBASE_128),
			SET_CASE(GR_TEXBASE_64),
			SET_CASE(GR_TEXBASE_32_TO_1),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grEnableMode_ce
		(EnumValue[]) {
			//typedef FxU32 GrEnableMode_t;
			SET_CASE(GR_MODE_DISABLE),
			SET_CASE(GR_MODE_ENABLE),
			SET_CASE(GR_AA_ORDERED),
			SET_CASE(GR_ALLOW_MIPMAP_DITHER),
			SET_CASE(GR_PASSTHRU),
			SET_CASE(GR_SHAMELESS_PLUG),
			SET_CASE(GR_VIDEO_SMOOTHING),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grCoordinateSpaceMode_ce
		(EnumValue[]) {
			//typedef FxU32 GrCoordinateSpaceMode_t;
			SET_CASE(GR_WINDOW_COORDS),
			SET_CASE(GR_CLIP_COORDS),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grDataStrips_ce
		(EnumValue[]) {
			/* Types of data in strips */
			SET_CASE(GR_FLOAT),
			SET_CASE(GR_U8),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grParams_ce
		(EnumValue[]) {
			/* Parameters for strips */
			SET_CASE(GR_PARAM_XY),
			SET_CASE(GR_PARAM_Z),
			SET_CASE(GR_PARAM_W),
			SET_CASE(GR_PARAM_Q),
			SET_CASE(GR_PARAM_FOG_EXT),

			SET_CASE(GR_PARAM_A),

			SET_CASE(GR_PARAM_RGB),

			SET_CASE(GR_PARAM_PARGB),

			SET_CASE(GR_PARAM_ST0),
			SET_CASE(GR_PARAM_ST1),
			SET_CASE(GR_PARAM_ST2),

			SET_CASE(GR_PARAM_Q0),
			SET_CASE(GR_PARAM_Q1),
			SET_CASE(GR_PARAM_Q2),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grMode_ce
		(EnumValue[]) {
			SET_CASE(GR_PARAM_DISABLE),
			SET_CASE(GR_PARAM_ENABLE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grVertex_ce
		(EnumValue[]) {
			//grDrawVertexArray/grDrawVertexArrayContiguous primitive type
			SET_CASE(GR_POINTS),
			SET_CASE(GR_LINE_STRIP),
			SET_CASE(GR_LINES),
			SET_CASE(GR_POLYGON),
			SET_CASE(GR_TRIANGLE_STRIP),
			SET_CASE(GR_TRIANGLE_FAN),
			SET_CASE(GR_TRIANGLES),
			SET_CASE(GR_TRIANGLE_STRIP_CONTINUE),
			SET_CASE(GR_TRIANGLE_FAN_CONTINUE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grGet_ce
		(EnumValue[]) {
			//grGet/grReset types
			SET_CASE(GR_BITS_DEPTH),
			SET_CASE(GR_BITS_RGBA),
			SET_CASE(GR_BITS_GAMMA),
			SET_CASE(GR_FIFO_FULLNESS),
			SET_CASE(GR_FOG_TABLE_ENTRIES),
			SET_CASE(GR_GAMMA_TABLE_ENTRIES),
			SET_CASE(GR_GLIDE_STATE_SIZE),
			SET_CASE(GR_GLIDE_VERTEXLAYOUT_SIZE),
			SET_CASE(GR_IS_BUSY),
			SET_CASE(GR_LFB_PIXEL_PIPE),
			SET_CASE(GR_MAX_TEXTURE_SIZE),
			SET_CASE(GR_MAX_TEXTURE_ASPECT_RATIO),
			SET_CASE(GR_MEMORY_FB),
			SET_CASE(GR_MEMORY_TMU),
			SET_CASE(GR_MEMORY_UMA),
			SET_CASE(GR_NON_POWER_OF_TWO_TEXTURES),
			SET_CASE(GR_NUM_BOARDS),
			SET_CASE(GR_NUM_FB),
			SET_CASE(GR_NUM_SWAP_HISTORY_BUFFER),
			SET_CASE(GR_NUM_TMU),
			SET_CASE(GR_PENDING_BUFFERSWAPS),
			SET_CASE(GR_REVISION_FB),
			SET_CASE(GR_REVISION_TMU),
			SET_CASE(GR_STATS_LINES),
			SET_CASE(GR_STATS_PIXELS_AFUNC_FAIL),
			SET_CASE(GR_STATS_PIXELS_CHROMA_FAIL),
			SET_CASE(GR_STATS_PIXELS_DEPTHFUNC_FAIL),
			SET_CASE(GR_STATS_PIXELS_IN),
			SET_CASE(GR_STATS_PIXELS_OUT),
			SET_CASE(GR_STATS_POINTS),
			SET_CASE(GR_STATS_TRIANGLES_IN),
			SET_CASE(GR_STATS_TRIANGLES_OUT),
			SET_CASE(GR_SWAP_HISTORY),
			SET_CASE(GR_SUPPORTS_PASSTHRU),
			SET_CASE(GR_TEXTURE_ALIGN),
			SET_CASE(GR_VIDEO_POSITION),
			SET_CASE(GR_VIEWPORT),
			SET_CASE(GR_WDEPTH_MIN_MAX),
			SET_CASE(GR_ZDEPTH_MIN_MAX),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grString_ce
		(EnumValue[]) {
			//grGetString types
			SET_CASE(GR_EXTENSION),
			SET_CASE(GR_HARDWARE),
			SET_CASE(GR_RENDERER),
			SET_CASE(GR_VENDOR),
			SET_CASE(GR_VERSION),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grScreenRefresh_ce
		(EnumValue[]) {
			//typedef FxI32 GrScreenRefresh_t
			SET_CASE(GR_REFRESH_60Hz),
			SET_CASE(GR_REFRESH_70Hz),
			SET_CASE(GR_REFRESH_72Hz),
			SET_CASE(GR_REFRESH_75Hz),
			SET_CASE(GR_REFRESH_80Hz),
			SET_CASE(GR_REFRESH_90Hz),
			SET_CASE(GR_REFRESH_100Hz),
			SET_CASE(GR_REFRESH_85Hz),
			SET_CASE(GR_REFRESH_120Hz),
			SET_CASE(GR_REFRESH_NONE),
			{ NULL, 0 } // sentinel
		}
	},
	{
		NULL, //grScreenResolution_ce
		(EnumValue[]) {
			//typedef FxI32 GrScreenResolution_t;
			SET_CASE(GR_RESOLUTION_320x200),
			SET_CASE(GR_RESOLUTION_320x240),
			SET_CASE(GR_RESOLUTION_400x256),
			SET_CASE(GR_RESOLUTION_512x384),
			SET_CASE(GR_RESOLUTION_640x200),
			SET_CASE(GR_RESOLUTION_640x350),
			SET_CASE(GR_RESOLUTION_640x400),
			SET_CASE(GR_RESOLUTION_640x480),
			SET_CASE(GR_RESOLUTION_800x600),
			SET_CASE(GR_RESOLUTION_960x720),
			SET_CASE(GR_RESOLUTION_856x480),
			SET_CASE(GR_RESOLUTION_512x256),
			SET_CASE(GR_RESOLUTION_1024x768),
			SET_CASE(GR_RESOLUTION_1280x1024),
			SET_CASE(GR_RESOLUTION_1600x1200),
			SET_CASE(GR_RESOLUTION_400x300),
			SET_CASE(GR_RESOLUTION_NONE),
			{ NULL, 0 }  // sentinel
		}
	},
	{ NULL, NULL } // sentinel
};


int enum_to_int(zend_object * enum_obj)
{
	for (int i = 0; grouped_enums[i].enum_entry != NULL; i++) {
		if (grouped_enums[i].enum_entry == enum_obj->ce) {
			const char* case_name = ZSTR_VAL(Z_STR_P(zend_enum_fetch_case_name(enum_obj)));
			int len = strlen(case_name);

			for (int j = 0; grouped_enums[i].values[j].name != NULL; j++) {
				if (len == strlen(grouped_enums[i].values[j].name)
					&& memcmp(case_name, grouped_enums[i].values[j].name, len) == 0
				) {
					return grouped_enums[i].values[j].value;
				}
			}

			zend_throw_error(NULL, "Unknown enum case");
			return 0;
		}
	}

	zend_throw_error(NULL, "Unknown enum case");
	return 0;
}

ZEND_METHOD(GrCombineFunction_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCombineFactor_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCombineLocal_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCombineOther_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrAlphaSource_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrColorCombineFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrAlphaBlendFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrAspectRatio_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrBuffer_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrChromakeyMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrChromaRangeMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTexChromakeyMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCmpFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrColorFormat_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCullMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrDepthBufferMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrDitherMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrFogMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLock_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLfbBypassMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLfbWriteMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrOriginLocation_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrLOD_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrMipMapMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrSmoothingMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureClampMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureCombineFnc_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureFilterMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTextureFormat_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTexTable_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrNCCTable_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrTexBaseRange_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrEnableMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrCoordinateSpaceMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrDataStrips_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrParams_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrMode_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrVertex_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrGet_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrString_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrScreenRefresh_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };
ZEND_METHOD(GrScreenResolution_t, toInt) { RETURN_LONG(enum_to_int(Z_OBJ_P(ZEND_THIS))); };


void phpglide3x_register_enums(INIT_FUNC_ARGS)
{
	//typedef FxI32 GrCombineFunction_t;
	grCombineFunction_ce = grouped_enums[0].enum_entry = register_class_GrCombineFunction_t();
		
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_ZERO);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_NONE);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_BLEND_OTHER);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_ADD_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_BLEND);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_OTHER_MINUS_LOCAL_ADD_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_BLEND_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FUNCTION_SCALE_MINUS_LOCAL_ADD_LOCAL_ALPHA);

	//typedef FxI32 GrCombineFactor_t;
	grCombineFactor_ce = grouped_enums[1].enum_entry = register_class_GrCombineFactor_t();
		
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ZERO);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_NONE);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_OTHER_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_TEXTURE_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_TEXTURE_RGB);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_DETAIL_FACTOR);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_LOD_FRACTION);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_OTHER_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_LOCAL_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_TEXTURE_ALPHA);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_DETAIL_FACTOR);
	CREATE_CONSTANT(GR_COMBINE_FACTOR_ONE_MINUS_LOD_FRACTION);

	//typedef FxI32 GrCombineLocal_t;
	grCombineLocal_ce = grouped_enums[2].enum_entry = register_class_GrCombineLocal_t();
		
	CREATE_CONSTANT(GR_COMBINE_LOCAL_ITERATED);
	CREATE_CONSTANT(GR_COMBINE_LOCAL_CONSTANT);
	CREATE_CONSTANT(GR_COMBINE_LOCAL_NONE);
	CREATE_CONSTANT(GR_COMBINE_LOCAL_DEPTH);

	//typedef FxI32 GrCombineOther_t;
	grCombineOther_ce = grouped_enums[3].enum_entry = register_class_GrCombineOther_t();
		
	CREATE_CONSTANT(GR_COMBINE_OTHER_ITERATED);
	CREATE_CONSTANT(GR_COMBINE_OTHER_TEXTURE);
	CREATE_CONSTANT(GR_COMBINE_OTHER_CONSTANT);
	CREATE_CONSTANT(GR_COMBINE_OTHER_NONE);

	//typedef FxI32 GrAlphaSource_t;
	grAlphaSource_ce = grouped_enums[4].enum_entry = register_class_GrAlphaSource_t();
		
	CREATE_CONSTANT(GR_ALPHASOURCE_CC_ALPHA);
	CREATE_CONSTANT(GR_ALPHASOURCE_ITERATED_ALPHA);
	CREATE_CONSTANT(GR_ALPHASOURCE_TEXTURE_ALPHA);
	CREATE_CONSTANT(GR_ALPHASOURCE_TEXTURE_ALPHA_TIMES_ITERATED_ALPHA);

	//typedef FxI32 GrColorCombineFnc_t;
	grColorCombineFnc_ce = grouped_enums[5].enum_entry = register_class_GrColorCombineFnc_t();
		
	CREATE_CONSTANT(GR_COLORCOMBINE_ZERO);
	CREATE_CONSTANT(GR_COLORCOMBINE_CCRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_ITRGB_DELTA0);
	CREATE_CONSTANT(GR_COLORCOMBINE_DECAL_TEXTURE);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_CCRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_DELTA0);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ITRGB_ADD_ALPHA);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_TIMES_ALPHA_ADD_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_ADD_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_TEXTURE_SUB_ITRGB);
	CREATE_CONSTANT(GR_COLORCOMBINE_CCRGB_BLEND_ITRGB_ON_TEXALPHA);
	CREATE_CONSTANT(GR_COLORCOMBINE_DIFF_SPEC_A);
	CREATE_CONSTANT(GR_COLORCOMBINE_DIFF_SPEC_B);
	CREATE_CONSTANT(GR_COLORCOMBINE_ONE);

	//typedef FxI32 GrAlphaBlendFnc_t;
	grAlphaBlendFnc_ce = grouped_enums[6].enum_entry = register_class_GrAlphaBlendFnc_t();
		
	CREATE_CONSTANT(GR_BLEND_ZERO);
	CREATE_CONSTANT(GR_BLEND_SRC_ALPHA);
	CREATE_CONSTANT(GR_BLEND_SRC_COLOR);
	CREATE_CONSTANT(GR_BLEND_DST_COLOR);
	CREATE_CONSTANT(GR_BLEND_DST_ALPHA);
	CREATE_CONSTANT(GR_BLEND_ONE);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_SRC_ALPHA);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_SRC_COLOR);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_DST_COLOR);
	CREATE_CONSTANT(GR_BLEND_ONE_MINUS_DST_ALPHA);
	CREATE_CONSTANT(GR_BLEND_RESERVED_8);
	CREATE_CONSTANT(GR_BLEND_RESERVED_9);
	CREATE_CONSTANT(GR_BLEND_RESERVED_A);
	CREATE_CONSTANT(GR_BLEND_RESERVED_B);
	CREATE_CONSTANT(GR_BLEND_RESERVED_C);
	CREATE_CONSTANT(GR_BLEND_RESERVED_D);
	CREATE_CONSTANT(GR_BLEND_RESERVED_E);
	CREATE_CONSTANT(GR_BLEND_ALPHA_SATURATE);
	CREATE_CONSTANT(GR_BLEND_PREFOG_COLOR);

	//typedef FxI32 GrAspectRatio_t;
	grAspectRatio_ce = grouped_enums[7].enum_entry = register_class_GrAspectRatio_t();

	CREATE_CONSTANT(GR_ASPECT_LOG2_8x1);
	CREATE_CONSTANT(GR_ASPECT_LOG2_4x1);
	CREATE_CONSTANT(GR_ASPECT_LOG2_2x1);
	CREATE_CONSTANT(GR_ASPECT_LOG2_1x1);
	CREATE_CONSTANT(GR_ASPECT_LOG2_1x2);
	CREATE_CONSTANT(GR_ASPECT_LOG2_1x4);
	CREATE_CONSTANT(GR_ASPECT_LOG2_1x8);


	//typedef FxI32 GrBuffer_t;
	grBuffer_ce = grouped_enums[8].enum_entry = register_class_GrBuffer_t();

	CREATE_CONSTANT(GR_BUFFER_FRONTBUFFER);
	CREATE_CONSTANT(GR_BUFFER_BACKBUFFER);
	CREATE_CONSTANT(GR_BUFFER_AUXBUFFER);
	CREATE_CONSTANT(GR_BUFFER_DEPTHBUFFER);
	CREATE_CONSTANT(GR_BUFFER_ALPHABUFFER);
	CREATE_CONSTANT(GR_BUFFER_TRIPLEBUFFER);

	//typedef FxI32 GrChromakeyMode_t;
	grChromakeyMode_ce = grouped_enums[9].enum_entry = register_class_GrChromakeyMode_t();

	CREATE_CONSTANT(GR_CHROMAKEY_DISABLE);
	CREATE_CONSTANT(GR_CHROMAKEY_ENABLE);

	//typedef FxI32 GrChromaRangeMode_t;
	grChromaRangeMode_ce = grouped_enums[10].enum_entry = register_class_GrChromaRangeMode_t();

	CREATE_CONSTANT(GR_CHROMARANGE_RGB_ALL_EXT);
	CREATE_CONSTANT(GR_CHROMARANGE_DISABLE_EXT);
	CREATE_CONSTANT(GR_CHROMARANGE_ENABLE_EXT);

	//typedef FxI32 GrTexChromakeyMode_t;
	grTexChromakeyMode_ce = grouped_enums[11].enum_entry = register_class_GrTexChromakeyMode_t();

	CREATE_CONSTANT(GR_TEXCHROMA_DISABLE_EXT);
	CREATE_CONSTANT(GR_TEXCHROMA_ENABLE_EXT);
	CREATE_CONSTANT(GR_TEXCHROMARANGE_RGB_ALL_EXT);

	//typedef FxI32 GrCmpFnc_t;
	grCmpFnc_ce = grouped_enums[12].enum_entry = register_class_GrCmpFnc_t();

	CREATE_CONSTANT(GR_CMP_NEVER);
	CREATE_CONSTANT(GR_CMP_LESS);
	CREATE_CONSTANT(GR_CMP_EQUAL);
	CREATE_CONSTANT(GR_CMP_LEQUAL);
	CREATE_CONSTANT(GR_CMP_GREATER);
	CREATE_CONSTANT(GR_CMP_NOTEQUAL);
	CREATE_CONSTANT(GR_CMP_GEQUAL);
	CREATE_CONSTANT(GR_CMP_ALWAYS);

	//typedef FxI32 GrColorFormat_t;
	grColorFormat_ce = grouped_enums[13].enum_entry = register_class_GrColorFormat_t();

	CREATE_CONSTANT(GR_COLORFORMAT_ARGB);
	CREATE_CONSTANT(GR_COLORFORMAT_ABGR);
	CREATE_CONSTANT(GR_COLORFORMAT_RGBA);
	CREATE_CONSTANT(GR_COLORFORMAT_BGRA);

	//typedef FxI32 GrCullMode_t;
	grCullMode_ce = grouped_enums[14].enum_entry = register_class_GrCullMode_t();

	CREATE_CONSTANT(GR_CULL_DISABLE);
	CREATE_CONSTANT(GR_CULL_NEGATIVE);
	CREATE_CONSTANT(GR_CULL_POSITIVE);

	//typedef FxI32 GrDepthBufferMode_t;
	grDepthBufferMode_ce = grouped_enums[15].enum_entry = register_class_GrDepthBufferMode_t();

	CREATE_CONSTANT(GR_DEPTHBUFFER_DISABLE);
	CREATE_CONSTANT(GR_DEPTHBUFFER_ZBUFFER);
	CREATE_CONSTANT(GR_DEPTHBUFFER_WBUFFER);
	CREATE_CONSTANT(GR_DEPTHBUFFER_ZBUFFER_COMPARE_TO_BIAS);
	CREATE_CONSTANT(GR_DEPTHBUFFER_WBUFFER_COMPARE_TO_BIAS);

	//typedef FxI32 GrDitherMode_t;
	grDitherMode_ce = grouped_enums[16].enum_entry = register_class_GrDitherMode_t();

	CREATE_CONSTANT(GR_DITHER_DISABLE);
	CREATE_CONSTANT(GR_DITHER_2x2);
	CREATE_CONSTANT(GR_DITHER_4x4);

	//typedef FxI32 GrFogMode_t;
	grFogMode_ce = grouped_enums[17].enum_entry = register_class_GrFogMode_t();

	CREATE_CONSTANT(GR_FOG_DISABLE);
	CREATE_CONSTANT(GR_FOG_WITH_TABLE_ON_FOGCOORD_EXT);
	CREATE_CONSTANT(GR_FOG_WITH_TABLE_ON_Q);
	CREATE_CONSTANT(GR_FOG_WITH_TABLE_ON_W);
	CREATE_CONSTANT(GR_FOG_WITH_ITERATED_Z);
	CREATE_CONSTANT(GR_FOG_MULT2);
	CREATE_CONSTANT(GR_FOG_ADD2);

	//typedef FxU32 GrLock_t;
	grLock_ce = grouped_enums[18].enum_entry = register_class_GrLock_t();

	CREATE_CONSTANT(GR_LFB_READ_ONLY);
	CREATE_CONSTANT(GR_LFB_WRITE_ONLY);
	CREATE_CONSTANT(GR_LFB_IDLE);
	CREATE_CONSTANT(GR_LFB_NOIDLE);

	//typedef FxI32 GrLfbBypassMode_t;
	grLfbBypassMode_ce = grouped_enums[19].enum_entry = register_class_GrLfbBypassMode_t();

	CREATE_CONSTANT(GR_LFBBYPASS_DISABLE);
	CREATE_CONSTANT(GR_LFBBYPASS_ENABLE);

	//typedef FxI32 GrLfbWriteMode_t;
	grLfbWriteMode_ce = grouped_enums[20].enum_entry = register_class_GrLfbWriteMode_t();

	CREATE_CONSTANT(GR_LFBWRITEMODE_565);
	CREATE_CONSTANT(GR_LFBWRITEMODE_555);
	CREATE_CONSTANT(GR_LFBWRITEMODE_1555);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED1);
	CREATE_CONSTANT(GR_LFBWRITEMODE_888);
	CREATE_CONSTANT(GR_LFBWRITEMODE_8888);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED2);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED3);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED4);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED5);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED6);
	CREATE_CONSTANT(GR_LFBWRITEMODE_RESERVED7);
	CREATE_CONSTANT(GR_LFBWRITEMODE_565_DEPTH);
	CREATE_CONSTANT(GR_LFBWRITEMODE_555_DEPTH);
	CREATE_CONSTANT(GR_LFBWRITEMODE_1555_DEPTH);
	CREATE_CONSTANT(GR_LFBWRITEMODE_ZA16);
	CREATE_CONSTANT(GR_LFBWRITEMODE_ANY);

	//typedef FxI32 GrOriginLocation_t;
	grOriginLocation_ce = grouped_enums[21].enum_entry = register_class_GrOriginLocation_t();

	CREATE_CONSTANT(GR_ORIGIN_UPPER_LEFT);
	CREATE_CONSTANT(GR_ORIGIN_LOWER_LEFT);
	CREATE_CONSTANT(GR_ORIGIN_ANY);

	/*
	typedef struct {
		int                size;
		void               *lfbPtr;
		FxU32              strideInBytes;
		GrLfbWriteMode_t   writeMode;
		GrOriginLocation_t origin;
	} GrLfbInfo_t;
	*/

	//typedef FxI32 GrLOD_t;
	grLOD_ce = grouped_enums[22].enum_entry = register_class_GrLOD_t();

	CREATE_CONSTANT(GR_LOD_LOG2_256);
	CREATE_CONSTANT(GR_LOD_LOG2_128);
	CREATE_CONSTANT(GR_LOD_LOG2_64);
	CREATE_CONSTANT(GR_LOD_LOG2_32);
	CREATE_CONSTANT(GR_LOD_LOG2_16);
	CREATE_CONSTANT(GR_LOD_LOG2_8);
	CREATE_CONSTANT(GR_LOD_LOG2_4);
	CREATE_CONSTANT(GR_LOD_LOG2_2);
	CREATE_CONSTANT(GR_LOD_LOG2_1);

	//typedef FxI32 GrMipMapMode_t;
	grMipMapMode_ce = grouped_enums[23].enum_entry = register_class_GrMipMapMode_t();

	CREATE_CONSTANT(GR_MIPMAP_DISABLE);
	CREATE_CONSTANT(GR_MIPMAP_NEAREST);
	CREATE_CONSTANT(GR_MIPMAP_NEAREST_DITHER);

	//typedef FxI32 GrSmoothingMode_t;
	grSmoothingMode_ce = grouped_enums[24].enum_entry = register_class_GrSmoothingMode_t();

	CREATE_CONSTANT(GR_SMOOTHING_DISABLE);
	CREATE_CONSTANT(GR_SMOOTHING_ENABLE);

	//typedef FxI32 GrTextureClampMode_t;
	grTextureClampMode_ce = grouped_enums[25].enum_entry = register_class_GrTextureClampMode_t();

	CREATE_CONSTANT(GR_TEXTURECLAMP_WRAP);
	CREATE_CONSTANT(GR_TEXTURECLAMP_CLAMP);
	CREATE_CONSTANT(GR_TEXTURECLAMP_MIRROR_EXT);

	//typedef FxI32 GrTextureCombineFnc_t;
	grTextureCombineFnc_ce = grouped_enums[26].enum_entry = register_class_GrTextureCombineFnc_t();

	CREATE_CONSTANT(GR_TEXTURECOMBINE_ZERO);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_DECAL);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_OTHER);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_ADD);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_MULTIPLY);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_SUBTRACT);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_DETAIL);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_DETAIL_OTHER);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_TRILINEAR_ODD);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_TRILINEAR_EVEN);
	CREATE_CONSTANT(GR_TEXTURECOMBINE_ONE);

	//typedef FxI32 GrTextureFilterMode_t;
	grTextureFilterMode_ce = grouped_enums[27].enum_entry = register_class_GrTextureFilterMode_t();

	CREATE_CONSTANT(GR_TEXTUREFILTER_POINT_SAMPLED);
	CREATE_CONSTANT(GR_TEXTUREFILTER_BILINEAR);

	//typedef FxI32 GrTextureFormat_t;
	grTextureFormat_ce = grouped_enums[28].enum_entry = register_class_GrTextureFormat_t();

	CREATE_CONSTANT(GR_TEXFMT_8BIT);
	CREATE_CONSTANT(GR_TEXFMT_RGB_332);
	CREATE_CONSTANT(GR_TEXFMT_YIQ_422);
	CREATE_CONSTANT(GR_TEXFMT_ALPHA_8);
	CREATE_CONSTANT(GR_TEXFMT_INTENSITY_8);
	CREATE_CONSTANT(GR_TEXFMT_ALPHA_INTENSITY_44);
	CREATE_CONSTANT(GR_TEXFMT_P_8);
	CREATE_CONSTANT(GR_TEXFMT_RSVD0);
	CREATE_CONSTANT(GR_TEXFMT_RSVD1);
	CREATE_CONSTANT(GR_TEXFMT_16BIT);
	CREATE_CONSTANT(GR_TEXFMT_ARGB_8332);
	CREATE_CONSTANT(GR_TEXFMT_AYIQ_8422);
	CREATE_CONSTANT(GR_TEXFMT_RGB_565);
	CREATE_CONSTANT(GR_TEXFMT_ARGB_1555);
	CREATE_CONSTANT(GR_TEXFMT_ARGB_4444);
	CREATE_CONSTANT(GR_TEXFMT_ALPHA_INTENSITY_88);
	CREATE_CONSTANT(GR_TEXFMT_AP_88);
	CREATE_CONSTANT(GR_TEXFMT_RSVD2);

	//typedef FxU32 GrTexTable_t;
	grTexTable_ce = grouped_enums[29].enum_entry = register_class_GrTexTable_t();

	CREATE_CONSTANT(GR_TEXTABLE_NCC0);
	CREATE_CONSTANT(GR_TEXTABLE_NCC1);
	CREATE_CONSTANT(GR_TEXTABLE_PALETTE);
	CREATE_CONSTANT(GR_TEXTABLE_PALETTE_6666_EXT);

	//typedef FxU32 GrNCCTable_t;
	grNCCTable_ce = grouped_enums[30].enum_entry = register_class_GrNCCTable_t();

	CREATE_CONSTANT(GR_NCCTABLE_NCC0);
	CREATE_CONSTANT(GR_NCCTABLE_NCC1);

	//typedef FxU32 GrTexBaseRange_t;
	grTexBaseRange_ce = grouped_enums[31].enum_entry = register_class_GrTexBaseRange_t();

	CREATE_CONSTANT(GR_TEXBASE_256);
	CREATE_CONSTANT(GR_TEXBASE_128);
	CREATE_CONSTANT(GR_TEXBASE_64);
	CREATE_CONSTANT(GR_TEXBASE_32_TO_1);

	//typedef FxU32 GrEnableMode_t;
	grEnableMode_ce = grouped_enums[32].enum_entry = register_class_GrEnableMode_t();

	CREATE_CONSTANT(GR_MODE_DISABLE);
	CREATE_CONSTANT(GR_MODE_ENABLE);
	CREATE_CONSTANT(GR_AA_ORDERED);
	CREATE_CONSTANT(GR_ALLOW_MIPMAP_DITHER);
	CREATE_CONSTANT(GR_PASSTHRU);
	CREATE_CONSTANT(GR_SHAMELESS_PLUG);
	CREATE_CONSTANT(GR_VIDEO_SMOOTHING);

	//typedef FxU32 GrCoordinateSpaceMode_t;
	grCoordinateSpaceMode_ce = grouped_enums[33].enum_entry = register_class_GrCoordinateSpaceMode_t();

	CREATE_CONSTANT(GR_WINDOW_COORDS);
	CREATE_CONSTANT(GR_CLIP_COORDS);

	/* Types of data in strips */
	grDataStrips_ce = grouped_enums[34].enum_entry = register_class_GrDataStrips_t();

	CREATE_CONSTANT(GR_FLOAT);
	CREATE_CONSTANT(GR_U8);

	/* Parameters for strips */
	grParams_ce = grouped_enums[35].enum_entry = register_class_GrParams_t();

	CREATE_CONSTANT(GR_PARAM_XY);
	CREATE_CONSTANT(GR_PARAM_Z);
	CREATE_CONSTANT(GR_PARAM_W);
	CREATE_CONSTANT(GR_PARAM_Q);
	CREATE_CONSTANT(GR_PARAM_FOG_EXT);

	CREATE_CONSTANT(GR_PARAM_A);

	CREATE_CONSTANT(GR_PARAM_RGB);

	CREATE_CONSTANT(GR_PARAM_PARGB);

	CREATE_CONSTANT(GR_PARAM_ST0);
	CREATE_CONSTANT(GR_PARAM_ST1);
	CREATE_CONSTANT(GR_PARAM_ST2);

	CREATE_CONSTANT(GR_PARAM_Q0);
	CREATE_CONSTANT(GR_PARAM_Q1);
	CREATE_CONSTANT(GR_PARAM_Q2);

	
	//typedef FxU32 GrEnableMode_t;
	grMode_ce = grouped_enums[36].enum_entry = register_class_GrMode_t();

	CREATE_CONSTANT(GR_PARAM_DISABLE);
	CREATE_CONSTANT(GR_PARAM_ENABLE);

	//grDrawVertexArray/grDrawVertexArrayContiguous primitive type
	grVertex_ce = grouped_enums[37].enum_entry = register_class_GrVertex_t();

	CREATE_CONSTANT(GR_POINTS);
	CREATE_CONSTANT(GR_LINE_STRIP);
	CREATE_CONSTANT(GR_LINES);
	CREATE_CONSTANT(GR_POLYGON);
	CREATE_CONSTANT(GR_TRIANGLE_STRIP);
	CREATE_CONSTANT(GR_TRIANGLE_FAN);
	CREATE_CONSTANT(GR_TRIANGLES);
	CREATE_CONSTANT(GR_TRIANGLE_STRIP_CONTINUE);
	CREATE_CONSTANT(GR_TRIANGLE_FAN_CONTINUE);

	//grGet/grReset types
	grGet_ce = grouped_enums[38].enum_entry = register_class_GrGet_t();

	CREATE_CONSTANT(GR_BITS_DEPTH);
	CREATE_CONSTANT(GR_BITS_RGBA);
	CREATE_CONSTANT(GR_BITS_GAMMA);
	CREATE_CONSTANT(GR_FIFO_FULLNESS);
	CREATE_CONSTANT(GR_FOG_TABLE_ENTRIES);
	CREATE_CONSTANT(GR_GAMMA_TABLE_ENTRIES);
	CREATE_CONSTANT(GR_GLIDE_STATE_SIZE);
	CREATE_CONSTANT(GR_GLIDE_VERTEXLAYOUT_SIZE);
	CREATE_CONSTANT(GR_IS_BUSY);
	CREATE_CONSTANT(GR_LFB_PIXEL_PIPE);
	CREATE_CONSTANT(GR_MAX_TEXTURE_SIZE);
	CREATE_CONSTANT(GR_MAX_TEXTURE_ASPECT_RATIO);
	CREATE_CONSTANT(GR_MEMORY_FB);
	CREATE_CONSTANT(GR_MEMORY_TMU);
	CREATE_CONSTANT(GR_MEMORY_UMA);
	CREATE_CONSTANT(GR_NON_POWER_OF_TWO_TEXTURES);
	CREATE_CONSTANT(GR_NUM_BOARDS);
	CREATE_CONSTANT(GR_NUM_FB);
	CREATE_CONSTANT(GR_NUM_SWAP_HISTORY_BUFFER);
	CREATE_CONSTANT(GR_NUM_TMU);
	CREATE_CONSTANT(GR_PENDING_BUFFERSWAPS);
	CREATE_CONSTANT(GR_REVISION_FB);
	CREATE_CONSTANT(GR_REVISION_TMU);
	CREATE_CONSTANT(GR_STATS_LINES);
	CREATE_CONSTANT(GR_STATS_PIXELS_AFUNC_FAIL);
	CREATE_CONSTANT(GR_STATS_PIXELS_CHROMA_FAIL);
	CREATE_CONSTANT(GR_STATS_PIXELS_DEPTHFUNC_FAIL);
	CREATE_CONSTANT(GR_STATS_PIXELS_IN);
	CREATE_CONSTANT(GR_STATS_PIXELS_OUT);
	CREATE_CONSTANT(GR_STATS_POINTS);
	CREATE_CONSTANT(GR_STATS_TRIANGLES_IN);
	CREATE_CONSTANT(GR_STATS_TRIANGLES_OUT);
	CREATE_CONSTANT(GR_SWAP_HISTORY);
	CREATE_CONSTANT(GR_SUPPORTS_PASSTHRU);
	CREATE_CONSTANT(GR_TEXTURE_ALIGN);
	CREATE_CONSTANT(GR_VIDEO_POSITION);
	CREATE_CONSTANT(GR_VIEWPORT);
	CREATE_CONSTANT(GR_WDEPTH_MIN_MAX);
	CREATE_CONSTANT(GR_ZDEPTH_MIN_MAX);
	
	//grGetString types
	grString_ce = grouped_enums[39].enum_entry = register_class_GrString_t();

	CREATE_CONSTANT(GR_EXTENSION);
	CREATE_CONSTANT(GR_HARDWARE);
	CREATE_CONSTANT(GR_RENDERER);
	CREATE_CONSTANT(GR_VENDOR);
	CREATE_CONSTANT(GR_VERSION);

	//typedef FxI32 GrScreenRefresh_t
	grScreenRefresh_ce = grouped_enums[40].enum_entry = register_class_GrScreenRefresh_t();

	CREATE_CONSTANT(GR_REFRESH_60Hz);
	CREATE_CONSTANT(GR_REFRESH_70Hz);
	CREATE_CONSTANT(GR_REFRESH_72Hz);
	CREATE_CONSTANT(GR_REFRESH_75Hz);
	CREATE_CONSTANT(GR_REFRESH_80Hz);
	CREATE_CONSTANT(GR_REFRESH_90Hz);
	CREATE_CONSTANT(GR_REFRESH_100Hz);
	CREATE_CONSTANT(GR_REFRESH_85Hz);
	CREATE_CONSTANT(GR_REFRESH_120Hz);
	CREATE_CONSTANT(GR_REFRESH_NONE);

	//typedef FxI32 GrScreenResolution_t;
	grScreenResolution_ce = grouped_enums[41].enum_entry = register_class_GrScreenResolution_t();

	CREATE_CONSTANT(GR_RESOLUTION_320x200);
	CREATE_CONSTANT(GR_RESOLUTION_320x240);
	CREATE_CONSTANT(GR_RESOLUTION_400x256);
	CREATE_CONSTANT(GR_RESOLUTION_512x384);
	CREATE_CONSTANT(GR_RESOLUTION_640x200);
	CREATE_CONSTANT(GR_RESOLUTION_640x350);
	CREATE_CONSTANT(GR_RESOLUTION_640x400);
	CREATE_CONSTANT(GR_RESOLUTION_640x480);
	CREATE_CONSTANT(GR_RESOLUTION_800x600);
	CREATE_CONSTANT(GR_RESOLUTION_960x720);
	CREATE_CONSTANT(GR_RESOLUTION_856x480);
	CREATE_CONSTANT(GR_RESOLUTION_512x256);
	CREATE_CONSTANT(GR_RESOLUTION_1024x768);
	CREATE_CONSTANT(GR_RESOLUTION_1280x1024);
	CREATE_CONSTANT(GR_RESOLUTION_1600x1200);
	CREATE_CONSTANT(GR_RESOLUTION_400x300);
	CREATE_CONSTANT(GR_RESOLUTION_NONE);

	CREATE_CONSTANT(GR_RESOLUTION_MIN);
	CREATE_CONSTANT(GR_RESOLUTION_MAX);

	CREATE_CONSTANT(FXTRUE);
	CREATE_CONSTANT(FXFALSE);
}